navigation:
  - text: Releases
    url: "#releases"
  # - text: Shows
  #   url: "#shows"
  - text: Contact
    url: "#contact"
  - text: Shop
    url: "http://rvsmusic.bandcamp.com"
  - text: We Comin' For You Cast
    url: "http://prowrestlingblack.org"
